---
- block:
  - name: install the desired debs
    include: "install_deb.yml"
    with_items: "{{ debs_to_install }}"

  - name: update apt cache
    apt:
      update_cache: yes

  - name: install unattended-upgrades
    apt:
      name: unattended-upgrades
      state: latest

  - name: run unattended-upgrades on a cron
    cron:
      name: "daily apt package security updates"
      minute: "0"
      hour: "0"
      job: "apt update && unattended-upgrade"
      user: root

  - name: add the necessary apt keys from keyservers
    apt_key:
      keyserver: "{{ item.keyserver }}"
      id: "{{ item.id }}"
    when: item.keyserver is defined
    with_items: "{{ keyservers_to_add }}"

  - name: add the necessary apt keys from urls
    apt_key:
      url: "{{ item.url }}"
    when: item.url is defined
    with_items: "{{ keyservers_to_add }}"

  - name: add necessary additional apt repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items: "{{ apt_repositories_to_add }}"
    register: add_apt_repositories_result

  - name: update cache for new repos
    apt:
      update_cache: yes
    when: add_apt_repositories_result.changed

  - name: install the desired packages
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages_to_install }}"


  - name: uninstall the desired packages
    apt:
      name: "{{ item }}"
      state: absent
    with_items: "{{ packages_to_uninstall }}"

  # @TODO(mattjmcnaughton) Determine a way to remove manually installed debs.

  - name: remove useless packages from cache
    apt:
      autoclean: yes

  - name: remove no longer required dependencies
    apt:
      autoremove: yes

  - name: run apt autoremove on cron
    cron:
      name: "daily apt autoremove"
      minute: "0"
      hour: "12"
      job: "apt autoremove -y"
      user: root

  become: true
